import path from "path";


export const SEND_TO_REWRITE_REQUEST_CONVERTER = 'SEND_TO_REWRITE_REQUEST_CONVERTER'
export const CHECK_CHANNELS_REQUEST_CONVERTER = 'CHECK_CHANNELS_REQUEST_CONVERTER'
export const REWRITE_CONTENT_REQUEST_CONVERTER='REWRITE_CONTENT_REQUEST_CONVERTER'


//CLIENT

export const REWRITER_CLIENT = 'REWRITER_CLIENT'


//FILE_MANAGER
export const CHECK_CHANNEL = 'CHECK_CHANNEL_ACTION'
export const GET_CHANNEL = 'GET_CHANNEL'
export const FILE_MANAGER_CONFIG = 'FILE_MANAGER_CONFIG'
export const FILE_MANAGER = 'FILE_MANAGER'
//

//CHANNEL-CHECKER
export const CHANNEL_CHECKER = 'CHANNEL_CHECKER'

//REPOSITORY
export const CHANNEL_REPOSITORY = 'CHANNEL_REPOSITORY'

//CONTENT AGENT
export const CONTENT_AGENT = 'CONTENT_AGENT'
//

//CUSTOMER-MANAGER
export const CUSTOMER_MANAGER = 'CUSTOMER_MANAGER'


